name: Transform Tokens
on:
  push:
    branches:
      - main
    paths:
      - 'tokens.json' # Solo se ejecuta si cambia este archivo

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Style Dictionary
        run: npm run build

      - name: Subir cambios al repo
        run: |
          git config --global user.name "Macaque Bot"
          git config --global user.email "bot@macaque.com"
          git add dist/variables.css
          git commit -m "style: actualizar variables css desde figma" || echo "No hay cambios"
          git push